API_ID = "YOUR_API_ID"
API_HASH = "YOUR_API_HASH"
ADMIN_ID = "YOUR_ADMIN_ID"
BOT_TOKEN = "YOUR_BOT_TOKEN"

BOT_USERNAME = "Automatic_posttbot"
FORCE_CHANNEL_USERNAME = "@iqra_music_support"
ADMIN_CONTACT_USERNAME = "AdsNova0"
